### ISSUE TITLE
[Suggestion] Add option in config to switch between forms and commands

### ISSUE THREAD

**Issue by AyzrixYTB** [AntiCores/EasyHomes#2]
Have the choice between the format message or GUI

**Comment by Thunder33345** [comment]
fun fact just use /home (name)
doing /home will open the UI
/home help will open the commands for non gui

**Comment by Ifera** [comment]
Yea. Like @thunder33345 said. You can use commands and forms both but ok will add the option later.

**Comment by Ifera** [comment]
Just do what thunder said. Having that option is redundant.
