### ISSUE TITLE
Does not support integer homes.

### ISSUE THREAD

**Issue by xDanub** [AntiCores/EasyHomes#5]
What I did: I tried to teleport to a home named ``` 1 ``` 
What I expected: to be teleported to that home
What i got: I got an error message saying it expected a string, and received an integer.

How to reproduce:
1. Install plugin
2. /home
3. Name this home “1”
4. /home 
5. Try to teleport/delete a home.

**Comment by Thunder33345** [comment]
Please tell us:
what you did
what you get
what you expected

Without these three information we cant really help you as we cannot read minds here
Will reopen when enough information is provided

**Comment by xDanub** [comment]
@thunder33345 Please reopen this issue, as I have updated it to your standards.

**Comment by Ifera** [comment]
I already knew this bug existed for quite some time now but never got around fixing it

**Comment by Ifera** [comment]
One can say that I am losing interest in maintaining these plugins... _that's the reason I haven't contributed to these as much as I did before._

**Comment by Thunder33345** [comment]
seems simple enough?
just cast anything into explicit string
with the new info i think i could attempt to fix it if you arent interested in doing so

**Comment by Ifera** [comment]
Yea its simple. You can proceed if you want

**Comment by xDanub** [comment]
It would be very helpful!

**Comment by Ifera** [comment]
Hmm so I can't reproduce this using commands looks like a form-only problem

**Comment by Ifera** [comment]
Should be fixed now
